name: "Comiple with QMK upstream"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  compile-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout QMK
        uses: actions/checkout@v7
        with:
          repository: qmk/qmk_firmware
          ref: master
          submodules: recursive
          path: qmk
      
      - name: Checkout rk/r65 source
        uses: actions/checkout@v7
        with:
          repository: Edduaardo/r65
          path: r65

      - name: Install QMK CLI
        run: curl -fsSL https://install.qmk.fm | sh -s -- --confirm --skip-qmk-toolchains --skip-udev-rules --skip-qmk-flashutils --skip-clean
      
      - name: Copy r65 source into QMK upstream
        run: cp -r r65/rk qmk/keyboards

      - name: Compile firmware
        uses: carlosperate/arm-none-eabi-gcc-action@v1.12.3
        with:
          release: 15.2.Rel1
      - run: make rk/r65
        working-directory: ./qmk
